import React, { useState } from 'react';
import { Brain, Loader2, CheckCircle2 } from 'lucide-react';
import { api } from '../utils/api';

type Question = { question: string; type: 'mcq' | 'fill'; options?: string[]; answer: string; related_vocab_ids?: string[]; related_words?: string[] };

export const QuizViewCloud: React.FC<{ onUpdated: () => void }> = ({ onUpdated }) => {
  const [tema, setTema] = useState('Kehidupan sehari-hari'); const [jumlah, setJumlah] = useState(10); const [tingkat, setTingkat] = useState('Sedang');
  const [questions, setQuestions] = useState<Question[]>([]); const [answers, setAnswers] = useState<string[]>([]); const [index, setIndex] = useState(0); const [score, setScore] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [history, setHistory] = useState<any[]>([]); const [message, setMessage] = useState('');
  const generate = async () => { setBusy(true); setMessage(''); setScore(null); try { const r = await api<{ data: { questions: Question[] } }>('/api/quiz', { method: 'POST', body: JSON.stringify({ action: 'generate', tema, jumlah_soal: jumlah, tingkat_kesulitan: tingkat }) }); setQuestions(r.data.questions || []); setAnswers([]); setIndex(0); } catch(e) { setMessage(e instanceof Error ? e.message : 'Gagal membuat soal.'); } finally { setBusy(false); } };
  const finish = async (nextAnswers = answers) => { const correct = questions.reduce((n,q,i) => n + (nextAnswers[i] === q.answer ? 1 : 0), 0); const nilai = questions.length ? Math.round(correct / questions.length * 100) : 0; setScore(nilai); setBusy(true); try { await api('/api/quiz', { method:'POST', body:JSON.stringify({ action:'submit', tema, tingkat_kesulitan:tingkat, nilai, questions, answers:nextAnswers }) }); onUpdated(); } catch(e) { setMessage(e instanceof Error ? e.message : 'Gagal menyimpan hasil.'); } finally { setBusy(false); } };
  const answer = async (value: string) => { const next = [...answers]; next[index] = value; setAnswers(next); if (index + 1 < questions.length) setIndex(index + 1); else await finish(next); };
  const loadHistory = async () => { try { const r = await api<{data:any[]}>('/api/quiz'); setHistory(r.data); } catch(e) { setMessage(e instanceof Error ? e.message : 'Gagal memuat riwayat.'); } };
  return <div className="max-w-4xl mx-auto space-y-6"><div className="bento-card p-6"><div className="flex items-center gap-2 mb-5"><Brain className="text-purple-300"/><h1 className="text-2xl font-bold">Latihan Soal AI</h1></div><div className="grid sm:grid-cols-3 gap-3"><input value={tema} onChange={e=>setTema(e.target.value)} className="p-3 rounded-xl bg-white/5 border border-white/10" placeholder="Tema"/><input type="number" min={1} max={50} value={jumlah} onChange={e=>setJumlah(Number(e.target.value))} className="p-3 rounded-xl bg-white/5 border border-white/10"/><select value={tingkat} onChange={e=>setTingkat(e.target.value)} className="p-3 rounded-xl bg-white/5 border border-white/10"><option>Mudah</option><option>Sedang</option><option>Sulit</option></select></div><button onClick={generate} disabled={busy} className="mt-4 px-5 py-3 rounded-2xl bg-purple-600 font-semibold flex items-center gap-2">{busy?<Loader2 className="animate-spin w-4 h-4"/>:<Brain className="w-4 h-4"/>} Generate Soal</button></div>
  {questions.length>0 && score===null && <div className="bento-card p-6 space-y-5"><div className="text-xs text-white/50">Soal {index+1}/{questions.length}</div><h2 className="text-xl font-semibold">{questions[index]?.question}</h2>{questions[index]?.type==='mcq' ? <div className="grid gap-3">{(questions[index].options||[]).map(o=><button key={o} onClick={()=>answer(o)} className="text-left p-4 rounded-xl bg-white/5 border border-white/10 hover:border-purple-500">{o}</button>)}</div> : <input autoFocus onKeyDown={e=>{if(e.key==='Enter') answer((e.currentTarget as HTMLInputElement).value)}} className="w-full p-4 rounded-xl bg-white/5 border border-white/10" placeholder="Ketik jawaban lalu Enter"/>}</div>}
  {score!==null && <div className="bento-card p-8 text-center"><CheckCircle2 className="w-10 h-10 mx-auto text-emerald-400 mb-3"/><h2 className="text-3xl font-bold">Nilai {score}</h2><p className="text-white/50 mt-2">Level kosakata terkait sudah diperbarui di D1.</p><button onClick={generate} className="mt-5 px-5 py-3 rounded-2xl bg-purple-600">Soal Lagi</button></div>}
  <div className="bento-card p-5"><button onClick={loadHistory} className="font-semibold">Riwayat Soal</button>{history.map(h=><div key={h.id} className="mt-3 flex justify-between text-sm border-t border-white/10 pt-3"><span>{h.tema}</span><span>{h.nilai} • {h.jumlah_soal} soal</span></div>)}</div>{message&&<div className="p-4 rounded-xl bg-red-500/10 text-red-200">{message}</div>}</div>;
};
