import React, { useEffect, useState } from 'react';
import { Save, Trash2 } from 'lucide-react';
import { api, authApi } from '../utils/api';

export const SettingsViewCloud: React.FC = () => {
  const [s,setS]=useState<any>({tema_warna:'purple',ukuran_font:'medium',target_harian:10,model_ai:'gemini-2.5-flash',bahasa_penjelasan:'id',speech_speed:1,show_romaja:1,auto_play_audio:0}); const [message,setMessage]=useState('');
  useEffect(()=>{api<{data:any}>('/api/settings').then(r=>setS(r.data)).catch(e=>setMessage(e.message));},[]);
  const save=async()=>{try{const r=await api<{data:any}>('/api/settings',{method:'PUT',body:JSON.stringify(s)});setS(r.data);setMessage('Pengaturan tersimpan.');}catch(e){setMessage(e instanceof Error?e.message:'Gagal menyimpan.');}};
  const del=async()=>{if(!confirm('Hapus seluruh akun, kamus, riwayat dan cerita? Tindakan ini permanen.'))return;await fetch('/api/account/delete',{method:'POST'});window.location.href='/login';};
  return <div className="max-w-3xl mx-auto space-y-6"><div className="bento-card p-6"><h1 className="text-2xl font-bold mb-6">Pengaturan</h1><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">Tema warna<select value={s.tema_warna} onChange={e=>setS({...s,tema_warna:e.target.value})} className="mt-2 w-full p-3 rounded-xl bg-white/5 border border-white/10"><option value="purple">Purple</option><option value="blue">Blue</option><option value="green">Green</option></select></label><label className="text-sm">Ukuran font<select value={s.ukuran_font} onChange={e=>setS({...s,ukuran_font:e.target.value})} className="mt-2 w-full p-3 rounded-xl bg-white/5 border border-white/10"><option value="small">Kecil</option><option value="medium">Sedang</option><option value="large">Besar</option></select></label><label className="text-sm">Target harian<input type="number" min="1" value={s.target_harian} onChange={e=>setS({...s,target_harian:Number(e.target.value)})} className="mt-2 w-full p-3 rounded-xl bg-white/5 border border-white/10"/></label><label className="text-sm">Model AI<input value={s.model_ai} onChange={e=>setS({...s,model_ai:e.target.value})} className="mt-2 w-full p-3 rounded-xl bg-white/5 border border-white/10"/></label><label className="text-sm">Bahasa penjelasan<select value={s.bahasa_penjelasan} onChange={e=>setS({...s,bahasa_penjelasan:e.target.value})} className="mt-2 w-full p-3 rounded-xl bg-white/5 border border-white/10"><option value="id">Indonesia</option><option value="en">English</option><option value="ko">Korea</option></select></label></div><button onClick={save} className="mt-6 px-5 py-3 rounded-2xl bg-purple-600 flex items-center gap-2"><Save className="w-4 h-4"/> Simpan</button>{message&&<p className="mt-4 text-sm text-white/60">{message}</p>}</div><div className="bento-card p-6"><h2 className="font-bold">Akun</h2><div className="flex flex-wrap gap-3 mt-4"><button onClick={authApi.logout} className="px-4 py-2 rounded-xl bg-white/10">Logout</button><button onClick={del} className="px-4 py-2 rounded-xl bg-red-500/15 text-red-300 flex items-center gap-2"><Trash2 className="w-4 h-4"/> Hapus semua data</button></div></div></div>;
};
