import React, { useState } from 'react';
import { BookOpen, Loader2 } from 'lucide-react';
import { api } from '../utils/api';

type Analysis = { surface:string; lemma:string; meaning:string; particles:string; role:string; explanation:string };
export const StoryViewCloud: React.FC = () => {
  const [tema,setTema]=useState('Kehidupan sehari-hari'); const [tingkat,setTingkat]=useState('Dasar'); const [data,setData]=useState<any>(null); const [selected,setSelected]=useState<Analysis|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const generate=async()=>{setBusy(true);setMessage('');try{const r=await api<{data:any}>('/api/stories',{method:'POST',body:JSON.stringify({tema,tingkat})});setData(r.data);}catch(e){setMessage(e instanceof Error?e.message:'Gagal membuat cerita.');}finally{setBusy(false);}};
  const parts=String(data?.isi_cerita_korea||'').split(/(\s+)/);
  return <div className="max-w-5xl mx-auto space-y-6"><div className="bento-card p-6"><div className="flex items-center gap-2 mb-5"><BookOpen className="text-purple-300"/><h1 className="text-2xl font-bold">Cerita Interaktif</h1></div><div className="grid sm:grid-cols-2 gap-3"><input value={tema} onChange={e=>setTema(e.target.value)} className="p-3 rounded-xl bg-white/5 border border-white/10" placeholder="Tema"/><select value={tingkat} onChange={e=>setTingkat(e.target.value)} className="p-3 rounded-xl bg-white/5 border border-white/10"><option>Dasar</option><option>TOPIK I</option><option>TOPIK II</option></select></div><button onClick={generate} disabled={busy} className="mt-4 px-5 py-3 rounded-2xl bg-purple-600 flex items-center gap-2">{busy?<Loader2 className="animate-spin w-4 h-4"/>:<BookOpen className="w-4 h-4"/>} Generate</button></div>{data&&<div className="bento-card p-7"><h2 className="text-2xl font-bold mb-2">{data.judul}</h2><p className="text-sm text-white/40 mb-6">Klik kata untuk melihat lemma, partikel/grammar, dan fungsi SPOK.</p><div className="text-lg leading-10">{parts.map((p:string,i:number)=>{if(!p.trim())return <span key={i}>{p}</span>;const a=(data.analysis||[]).find((x:Analysis)=>x.surface===p.replace(/[.,!?]/g,''));return a?<button key={i} onClick={()=>setSelected(a)} className="mx-0.5 underline decoration-purple-400 decoration-2 underline-offset-4 hover:text-purple-300">{p}</button>:<span key={i}>{p}</span>})}</div>{selected&&<div className="mt-7 p-5 rounded-2xl bg-purple-500/10 border border-purple-500/30"><div className="flex justify-between"><b>{selected.surface} → {selected.lemma}</b><button onClick={()=>setSelected(null)}>×</button></div><p className="mt-2">Arti: {selected.meaning}</p><p className="mt-1">Partikel/grammar: {selected.particles}</p><p className="mt-1">Peran: {selected.role}</p><p className="mt-1 text-white/60">{selected.explanation}</p></div>}</div>}{message&&<div className="p-4 rounded-xl bg-red-500/10 text-red-200">{message}</div>}</div>;
};
